var btn = document.querySelector("button");
    var out = document.getElementById("output");
    
  
    btn.addEventListener("click", getWord);
   
    function getWord(){
     
      
      var theWord= [
        
        // WEBCOMIC
        /// FEFERI
'fef',
'hey',
'glub',
'yeah',
'wwhat',
'hm',
'nothins on my mind wwhy cant i just fuckin talk and glub at you for a reason i dont havve',
'wwell fine but you dont wwant to hear it',
'uhuh wwhatevver',
'yeah wwell ok since wwe are the PALEST OF PALS A GUY COULD EVVER ASK FOR',
'i wwill tell you',
'evven though you wwill only humor me as usual since you dont agree wwith my agenda',
'any of my agendas really',
'none of the agendas none of them',
'see',
'more condenscension',
'you are goin to make a hell of an empress',
'so',
'i got to keep tryin thats howw all the great military masterminds became great through upright persevverance',
'it isnt wwrong',
'im not going to explain it to you again',
'at this point all you need to knoww is its important to me',
'and im doing it for us',
'i mean our kind',
'nobody understands not evven you',
'pshh',
'hemospectrum begs to differ',
'wwhatevver',
'i havve to keep an eye on em up here',
'its all about tactics',
'history is full of cases wwhere conquerers consort wwith members of the enemy in a mannerly wway before wwipin them out',
'evven goin as far as growwin fond a some',
'its only civvilized',
'all your feelins are fishy',
'GLUBGLUBGLUBGLUBGLUBGLUB',
'ill glub in wwhatevver dumbass bubbly soundin fishnoise i wwant to glub',
'ok please lets just not get into the wwhole fuckin fish pun thing again ok like wwe get it wwe are nautically themed',
'but yeah i dunno',
'i dont knoww wwhy she ignores me i guess shes just bored wwith me',
'wwe had it all set up for her to givve me this thing tonight that probably doesnt evven wwork but yeah maybe that wwasnt the point',
'i mean you think wwe havve a pretty good rivvalry goin right',
'or at least had',
'it wwas pretty fuckin bitter and contentious for a wwhile there and there wwas some good chemistry i dont knoww wwhat happened',
'it doesnt matter like i said shes bored shitless',
'i guess im not as good a advversary as i thought',
'ehhh',
'wwell ok thanks for sayin so',
'shrug',
'maybe',
'seems kinda odd though',
'fine',
'wwell those are my stupid feelins wwhat about yours',
'seems to me like you get along too wwell wwith evverybody to be harborin any black sentiments',
'yeah',
'oh god',
'uh',
'ok fef',
'this is NONE OF YOUR DAMN BUSINESS',
'i gotta go',
'be back later wwhen its time to play', 
'fef are you in',
'that took forevver',
'i wwas gettin wworried kinda',
'man that guy',
'hes a fuckin drama machine it is fuckin pathetic',
'fuck SORRY',
'yeah sorry',
'i wwas just really wworried and stressed out i thought you wwere dead',
'and i didnt evven get to thank you for savvin my life or really for anythin',
'and i just spent all this time here wworryin and thinkin about stuff',
'and i decided i havve something i wwant to tell you that ivve been meaning to get off my nub for a wwhile noww',
'wwhoa really',
'uh',
'wwhat is it',
'you go first',
'yeah i knoww',
'its ok maybe i wwill understand more than you think',
'wwe might evven be sayin the same thing',
'wwhoa',
'wwait',
'wwhat',
'fuck',
'this isnt what',
'i dont knoww i wwasnt expectin this at all',
'im not sure i can handle this',
'no',
'please dont',
'look im bein serious here dont do this',
'i wont even use my weird accent while i type ok so you know im bein really dead serious and honest about this',
'ok good',
'are you sure you arent bein hasty about this youve just been through a lot',
'i mean we are supposed to be fated to be moirails arent we',
'isnt that how it works',
'you cant just throw all that away cause youre sick of me',
'I DIDNT EVER NEED ANYONE TO LOOK AFTER ME',
'i was totally fuckin fine my ambitions were noble and really none of your fuckin business QUITE FRANKLY your majesty',
'and the only reason i put up with stickin my flipper in this fuckin shithole quadrant with you was',
'nevermind',
'ok fine',
'i apologize for losin my shit over this i was just caught off guard is all',
'but maybe its a good thing really',
'actually i might a been proposin the same thing to be honest',
'yeah',
'fef have you thought about',
'since you dont wanna be pale with me no more',
'the possibility a some other type of arrangement with me',
'i mean somethin a bit more kinda reddish like brighter red',
'ok well what do you think about it',
'now that youre thinkin about it',
'why not i thought you said you liked me',
'couldnt it be though',
'dont you think theres room in your collapsin and expandin bladder based aquatic vascular system for those feelins',
'oh god',
'im the biggest fuckin idiot who ever lived',
'i cant BELIEVE i just opened up to you like a chump when i knew what was comin',
'i am one sad fuckin brinesucker overemotional sappy trash youre right im not better than anybody',
'im worse than anybody EVERYBODY all the bodies',
'i cannot BELIEVE you are doin the fish pun thing while youre breakin up with me real nice whoops i mean REEL nice',
'wwait',
'dont go',
'glub',
'thats an astonishin accusation howw could you say that',
'first as if this scum is evven wworthy of a rivvalry wwith me and second as if im not totally DONE wwith you like i havve TOLD you REPEATEDLY',
'all i wwant to do is havve a wword wwith you',
'thats wwhat you nevver got fef',
'you and i are bein civvil by vvery vvirtue a the fact that wwere talkin noww',
'wwere royalty you and i and wwe belong together evven if not in THAT WWAY wwhich i get that youre not into and thats fine but wwe belong together as the rulin class if nothin else',
'so im gonna ask you this one last time and givve you the choice',
'im about to go please come wwith me',
'of course i wwas',
'and wwe should do it together',
'youvve got nothin to fear noww ivve reached a neww heights of powwer no one else can dream of not evven mindfang wwith her garish orange swweatsuit and her silly flappy wwings and all her poppycock about luck wwhich evveryone wwith a think pan knowws to be the fakest fiction that evver failed to exist',
'fight him',
'are you fuckin nuts',
'i slaughtered enough angels to knoww my limits and wwhere i stand against the lord of all angels they prophecized',
'of course im not gonna fight him i stand no chance in hell against that guy',
'im goin to join him',
' and youre gonna join me in joinin him too fef come on lets go',
'as the prince of hope im uniquely qualified to recognize wwhen all hope is lost',
'and im tellin you there is no hope not evven a little bit',
'only thing left to do is servve him and hope he spares us and im extendin the invvitation to come wwith me cause evven though you dont think so i really do care about you',
'servvin under jack together wwell be unstoppable and our anemones wwill tremble before us wwhat do you say',
'dont take that tuna vvoice wwith me princess',
'so thats howw it is is it',

        /// CRONUS
'wwhoa man could you maybe stop bumpin me wwith your codpiece',
'wwait are you actually seriously hittin on me',
'wwoww dude evven i think youre trash',
'sigh fine lets go out on a date i guess. flippin amazin this tragic scenarios wwhat i been reduced to',

        /// GAMZEE
'gam i need to talk to kar wwhere is he he isnt answwerin',
'i dont feel comfortable wwith that',
'i havve some serious feelins and problems here and i need some advvice',
'wwhy',
'wwhat the fuck do you mean by that are you sayin hes dead',
'oh fuck oh god fuck noww i feel like an asshole',
'that is the wworst fuckin advvice',
'wwhat an awwful thing a you to say',
'MAGIC ISNT REAL STUPID STOP BELIEVVIN IN IT',
'this is a lot a pointless fuckin rubbish and isnt no emotional help to him or me either for that matter',
'put kar on',
'i dont knoww',
'it probably doesnt matter',
'my feelins seem petty and meaninless noww',
'she had better things to wworry about than my ovverwwrought bullshit',
'like the dead guy wwho savved her',
'so forget it thanks anywway',
'wwhat the FUCK are you fuckin babblin about',
'are you recommendin a bevverage to me or somethin is that wwhat this is',
'i dont havve a fuckin faygo you stupid fuck wwhy wwould i keep that disgusting shit on hand',
'oh',
'oh god youre right i do i totally forgot about it',

        /// VRISKA
'hey',
'wwhats up',
'yup',
'god damn vvris wwhys it still got to be so flippin awwkwward like this come on',
'wwe used to havve a good thing goin remember our campaigns',
'that shit wwas epic wwhere are you evven goin to find a rivvalry like that',
'oh as if im not so ovver it please spare me your disdain mindfang',
'im wworkin on findin a neww rivvalry wwhichll make ours look like a kiddie game wwhich oh by the wway IT WWAS',
'fuck that fuckin wwitch bleww up my computer.',
'ok not literally the wwitch as in thats not literally her title or anythin',
'the seer i guess',
'fuckin lousy no good goddamn rotten seer',
'shut your spidertrap wwitch there are serious emotions happening ovver here',

        /// TEREZI
'hey ter can you go givve that four horned mustard blooded land licking sack of rubbish ovver there a message for me',
'tell him to put his honey wwhere his mouth is and meet me outside for another duel',
'swweet stinkin murder i am truly pathetic arent i',

        /// KANAYA
'kan make her talk to me do somethin',
'your no good connivvin fuckin backstabbin girl crush thats wwho',
'pshhhhhh that is a fuckin laugh and you knoww it evveryone does',
'so help me out tell her to talk to me i think she blocked me you got to',
'wwhatEVVER you are so the vvillage twwo wwheel devvice wwhen it comes to auspisticing',
'you cant let a grudge go by you wwont stick your busy stem betwwixt so get wwith the program fussyfangs',
'wwho givves a shit wwhy she blocked me or about my fuckin manners come on youvve got a wway wwith her',
'i figure if youre going to auspisticize any twwo brinesuckers wwho sneer at each other a funny wway you might as wwell make it official and be ours right',
'she made me somethin per a prior arrangement',
'she wwill delivver it wwhen wwe meet in this game but i dont knoww wwhat the logistics are yet',
'im tryin to connoiter wwith her here but shes blowwin me off again fickle dirtscrapin landhag',
'kan stupid wwhat do you think its a fuckin gizmo to bloww up the wworld or somethin',
'ok wwell not that obvviously',
'but somethin thatll kill all land dwwellers wwhat else wwould i be after',
'wwell im not goin to vvery wwell kill you am i that wwould be fuckin unconscionable wwhat kind of friend wwould i be',
'yeah go ahead and kiss us off but therell be blood on your hands',
'you could either play along as our auspistice and do a little mediating like you wwere fuckin hatched to',
'or wwatch she and me devvolvve into fuckin full fledged kismesisses the kind like you dont get once in ten thousand swweeps',
'you knoww thats wwhat it wwould be there wwould be rainboww rivvers runnin through star systems and all nebulizin like liquid firewworks',
'it wwill be beautiful and heartbreaking all at once',
'you should read up on your history instead of poring through that godawwfull sunny rubbish',
'yeah it does its important sorry but the fate of the race and purity of the bloodline is important excuse me for being concerned',
'huh wwell ok',
'ordinarily id call bullshit on terrible stinkin bs like that but i knoww you dont really lie about stuff',
'unless its to yourself',
'but thats wwhy i bother evven talking to you i wwouldnt evven be here SAYIN any of this otherwwise',
'so did your clouds tell you that',
'i got clouds and they dont tell me SHIT they hide nothin but misfortune and monstrosities fuckin pain in the ass fuckin clouds',
'so howw do you knoww then',
'ok wwell you are jacked tight the fuck into this thing in so many wways i dont knoww wwhat to say anymore',
'wwhatevver wwe wwill just play and find out i guess',
'so can you tell her to talk to me anywway',
'god dammit she and me are teammates wwevve got to havve a powwwwoww or SOMETHING',
'fuck fine i get it ill step off',
'you dont wwant to be our auspistice cause you dont wwant to get locked into that sort of relation wwith her i can respect that',
'yeah it is your real feelins run pretty awwful RUDDY methinks evverybody knowws it',
'especially that assblood karkat he and me havve you so pegged about that its upright silly',
'but its cool its totally fine dont wworry ill leavve you alone and givve you a shot',
'wwhat wwhoa wwait wwho',
'ok wwait did she talk to you today wwhat did she say or glub or wwhatevver',
'WWWWHAT',
'wwait did she actually say that in confidence',
'can you copy exactly wwhat she said',
'this is bullshit youre bee essing me in some wway awwful',
'you dont lie but you do tease and ill tranfuse my kickass royal blood out wwith incontinent musclebeast discharge if i wwont knoww wwhen im gettin hooked',
'awwww fuck',
'see im tellin you',
'you got to play your cards right',
'if youre not savvvvy about howw you define yourself to people',
'you can just splash into the moirail zone before you knoww wwhich wways upwward',
'kan its hard being a kid and growwing up its hard and nobody understands',
'kan i been meanin to thank you',
'for all that trainin you did',
'i wwouldnt be the incredible holy wwizard i am noww wwithout your help',
'yeah wwell thats all i needed i guess',
'i just needed for someone to showw a little faith in me so im sayin thanks i owwe ya',
'dont wworry im all ovver that shit you dont evven knoww',
'wwhat',
'haha damn kan if thats your idea of offense bein made then i honestly gotta fuckin wworry for you',
'tell you wwhat ill givve you some lessons in dealin out the dark umbrage to repay you for your tutelage in the wwhite science',
'hey wwhat are you doin anywway',
'wwhats that thing there',
'that sounds           hopeful',
'you should of told me about this',
'if theres goin to be any sort a hope for our race as the prince of hope i demand to be invvolvved so dont go anywwhere wwithout me got it',

        /// KARKAT
'hey sorry for bustin in on the memo but i cant get ahold of you youre not answwerin',
'gams advvice is fuckin useless all he told me wwas to enjoy a bevverage i mean its not evven that bad its just soda but wwhatevver this isnt the point',
'i knoww i knoww its just i got a problem wwith feferi and im really kinda sittin here in bad shape about it emotionally speakin',
'wwhat a fuckin vvulgar display this is',
'airin out all his dirty laundry like that puttin a big fuckin pile a horns in the middle of the room',
'at least i got the upright basic decency to hide my shitty wand pile somewwhere in the lab you wwont find it dont evven bother lookin',
'its not magic wwe talked about this kar',
'i dont fuckin need this from you i take enough shit as it is from the rest a you dirtscrapers i thought you and me had a kinda pact or wwhatevver',
'nobody gets it',
'i had a harder time than anybody wwith this game',
'it wwas really fuckin unfair wwhat challenges i got saddled wwith',
'i wwoulda fuckin MURDERED for a land full of a lot a harmless brains and fire',
'but no it wwas so lonely',
'hey guys anybody wwant to come hang out wwith me in the land a wwrath and angels anybody at all i knoww it isnt anythin like one of your flippin land picnics anybody please ill evven settle for the kittycat shipper cavve girl',
'but yeah i guess bein her servver player and savvin her life wwasnt goddamn enough',
'had to be my most humiliatin rejection yet',
'yeah i guess',
'i knoww kar its not evven the point im ovver that embarrassment',
'im just saying wwhere the fuck wwere you guys i had to deal wwith those awwful angels all by my self',
'do you havve any idea howw hard those assholes are to kill',
'like at least a minute of sustained fire from only the most legendary wweapon evver and they wwere FAST and ANGRY as SHIT',
'fine wwhatevver your still missin the point',
'wwhere wwas evverybody wwhy are they avvoidin me all the time',
'wwell i wwoulda but nobody else wwas vvolunteerin to pick up the slack on angel killin duties',
'and anywways i did leavve evventually',
'yeah ok wwe wwill see wwhos becomin the proud neww recipient a wwhose ass noww',
'a magic wwand is that so',
'kar come on noww evveryone fuckin KNOWWS this memos rubbish',
'wwevve got a pact',
'wwhoa kar this is nothin if not flatterin but dont you think youre comin on a little strong',
'i mean yeah obvviously i kneww you wwerent serious',
'i guess i appreciate the effort youre puttin into cheerin me up',
'i can alwways count on you for some good ironic repartee kar nobody else really gets our sense a humor',
'are you busy',
'you said youd try to make it to lowwaa soon wwell howw about it',
'oh hahaha yeah losin track a the time shit is easy wwhen wwe start riffin like this kar',
'im just lonely here and i got major ordeals to keep afloat wwith',
'im sayin it wwould be cool to hang out and you said you wwould',
'can you put in a wword wwith your past self maybe buggin him to make the trip wwhen he gets the chance',
'wwhat',
'hey im not spyin you bein anythin but cagey wwhat wwith this wwhole line a humor and all',
'evven if i wwasnt compelled to think you wwere still bein flippant and ironic wwith me you cant exactly outright reject me can you',
'cause youre future you',
'doesnt count unless its present you til then its all fair game',
'just send past you ovver man wwell hang out',
'its not like im doin anythin right noww',
'wwhats that mean',
'no',
'wwell uh',
'therere just so damn many kar and theyre not gettin any less bloody pissed is the thing',
'kar im gettin some seriously mixed signals here',
'wwhat to wwho',
'wwho man wwhat are you talkin about',
'wwhat youre not makin sense',
'yeah i knoww wwhat its like you wwanna talk about it',

        /// SOLLUX
'hey finless this doesnt concern those wwith mustard sludge slippin through their vveins',
'its a matter for royalty only',
'so keep your mouth closed or ill slit you open ovver my next meal',
'wwas that slander just i heard i cant evven tell',
'i tend to block out noise from filth wwhose blood is practically the complementary fuckin color a mine',
'bring it mage',
'no its a shitty battle royale pass it on you dirtscrapin sack of honey dijon rubbish',

        /// ROSE
'wwho are you tryin to convvince wwith this ludicrous poppycock',
'magic is NOT REAL',
'wwhatevver youre doin its not real its somethin else outright entirely',
'its fancy and impressivve and all but its not the fuckin figmental storybook claptrap you wwanna make out like it is',
'so howw about you get off your high skyhorse',
'youre not usin magic just DEAL WW IT',
'ok i didnt say that',
'i think you wwear the role pretty wwell wwhich is somethin i can appreciate',
'theres a lot of showwmanship thats put in to comin off as a diabolical sort',
'wwell fine you dont havve to behavve vvillainous if youre bent up on actin against the grain a your nobility or somesuch',
'i can play that role its not like i evver didnt get my gils dirty before',
'wwell arent you',
'the wway you',
'ok',
'obvviously you got rich blood so maybe when you crash landed you wwerent recognized for it by wwhatevver vvehicle upholds the class structure in human society',
'must of been fuckin brutal raisin up a commonblood wwhen you knew you wwere better than evverybody and its probably got you all messed up inside but maybe theres hope for you',
'see i got a lot a experience bein nobility so ill let you knoww if you got a shot in hell at cuttin it pinkscarf',
'fakemage pinkscarf howw does that sound',
'see this is good i think this could be a good thing',
'this thing wwe got goin',
'you obvviously hate me and i think i got it in me to get the dark propensities smolderin',
'and wwere both obvviously dangerous elites in nature',
'i think theres somethin there i mean look at howw you evven came into the wworld',
'killed a fuckin fuck ton of marine life accidental',
'doin thats all i evver done practically the ocean wwas my killin cauldron',
'hahahahaha see youre good wwith fish puns too i got so many a those you havve no idea',
'i just think theres a fate thing here',
'i mean i dont mean to strike you as too forwwardsuch but are you seein wwhere im goin wwith this',
'look i understand you dont understand that kind of thing in your culture i get that',
'but maybe i could teach you to get it',
'yeah and in return maybe you could teach me howw to bullshit magic like that',
'yes teach me your secrets wwitch',

        /// JADE

'noww that youre done makin all that pointless rubbish',
'ivve got somethin wway more wworth your wwhile',
'that couldvve been anyone',
'lets not get distracted by your sad league of suitors and their flushed desperations',
'im offerin you the edge here in your rivvalry wwith the other female',
'wwevve got the same abstratus',
'and i dont need this thing anymore',
'since i became more powwerful than you could evver imagine as a mighty wwizard of wwhite science',
'so you might as wwell take it and settle your score wwith that awwful wwitch',
'yeah ok the seer then if you wwant to be dealin wwith technicalities',
'oh',
'wwell fuck',
'suppose i wwas guessin it wwas natural to presume somesuch relation like that betwween the twwo a you',
'oh i see so she shared her "magic secrets" wwith you then',
'its probably a trap i wwouldnt trust her',
'she is a cunnin and treacherous sort trust me i knoww her type',
'you are slingin around such a bloody mess of slander wwith these accusations',
'you wwouldnt understand anywway',
'its already been painfully established you people cant get your shalloww think pans under the majesty of our quadrants',
'if you must knoww things betwween us wwere gettin pretty bellicose and im pretty sure she wwas wwaxin as obsidian for me as a human got it in em to do',
'and if not for the interdimensional divvide keepin us apart honestly i dont doubt our rivvalry could be brewwin outright pitch',
'but the thing is i need a rivval wwho can pose me a challenge',
'and frankly shes not evven fit for holdin my cape anymore',
'at this point i find all her adorable black pixie dabblins to be prime kiddie playtime shit',
'all of her FRAUDULENT MAGICS cannot come close to posin threat to my mastery ovver the TRUEST SCIENCES',
'an wwith my empiricists wwand i servve as the righteous hope that wwill incinerate delusion and the deluded alike',
'my holy fire is the wwhite fury bled from the wwrath-wweary eyes of fifty thousand nonfictional angels',
'and wwhen theyre finished wweepin they wwill boww before their prince',
'so really you should be honored to inherit my old callin',
'both my armaments and my feud',
'itll be wwitch against wwitch',
'a real one vvs an impostor',
'faker one dies',
'oh wwill you just take the fuckin gun already',
'its a wway more powwerful wweapon than any of that crap you made',
'its a legendary relic wwithout equal',
'youre bein needlessly fuckin stubborn about this im doin you a fuckin favvor here',
'if you accept it this is the last ill evver be botherin you about anythin ok',
'FFFFFFWW',
'thats the code',
'howws that possible',
'its a one of a kind wweapon plundered from an alternian ghost ship',
'probably a cheap imitation of the original uh kind of like that one there is',
'so theres your answwer stable loops ahoy',
'noww enjoy the utter fuckin domination it affords',
'wwhos that',
'wwhy',
'wwhat the fuck is a grandson is that some kind of pervverse human familial thing',
'nevvermind then your procreational biologistics make my fins curl in distaste',
'settle dowwn jade youre radically underestimatin the amount of shit i dont givve about this',
'ill havve you knoww this is the last time im plannin on talkin to any human',
'i got bigger ships to sink and soon wwhen im good and ready me and my luminous fuckin science stick havve got a date wwith jack noir AND NO NOT THAT KIND OF DATE GIVVE ME A LITTLE FUCKIN CREDIT',
'wwhys this matter so hush hush anywway',
'wwell maybe he didnt wwanna disrupt wwhatevver disgustin sequence of evvents wwas responsible for his spawwnin in the first place',
'ok i think im startin to feel ill talkin about things makin me fathom pink wwigglers comin out a your owwn personal torso',
'so change a fuckin subject',
'that gun i just gavve you is somethin of a hatchright to the kid',
'happy i could play a role in your dirty stinkin lineage',
'no wwe dont knoww our direct forebears and im pretty sure any attempt to seek out or evven inquire about the supplier of your genes wwould be a fine wway to get yourself killed',
'but wwevve got our lore and it says wwe all got indivvidual ancestors wwho contribute to most of our genes abovve and beyond wwhat the grubs slurry does',
'oh shut up',
'anywway a lot of us believve wwere meant to trace the footsteps of those ancestors evven though wwe can nevver knoww em and on that journey wwe can come across belongings they once had cause wwe wwere hatched to find em and finish their wwork',
'i kinda think thats wwhy i found the gun in the first place',
'but noww im forsakin it because fuck i just found a better destiny than my old crappy one wwhich i nevver got any appreciation for anywway',
'wwhat do you mean',
'aww man come on',
'god damn it',
'its like you people go out of your wway to think a howw to disrespect me',
'fine fuck it wwhat do i care',
'this has been a completely flippin useless exchange as havve they all been wwith your species',
'and for the record evven though i said that stuff about bein fated to find my gun fate isnt real its a lot of FAKE FUCKIN HORSEFEATHERS',
'noww go and be cleansed by the light of truth purity nonfakeness hope and abovve all SCIENCE',

        /// PESTERQUEST

'its ok i got this',
'wwell i didnt ask for your opinion on wwhether the midblood wwanted my help or not',
'alright that does it ivve had enough of this wwishywwashy lawwnmeal nonsense',
'wwhy dont you make me',

        /// PARADOX SPACE
            // CRITICAL MISS - PARADOX SPACE
'MINDFANG you wwouldnt dare',
'fine i cross your ropes before you can',
'FUCK',
'wwhatevver i fire my rifle at your boww',
'I KNOWW SHUT UP',
'FUCKIN SHUT UP WWHALE',
'you filthy cerulean cheat yes i knoww you use loaded dice plus im not sure about that attack evven i dont remember you havvin cannons before',
'howw dare you talk to me that wway',
'WWHAT',
'NO WWAY NO FUCKIN WWAY',
'do you havve any idea howw hard it is to find lowwbloods wwillin to stop strokin their shame globes long enough',
'i knoww you just wwant to feed them to your lusus if you do that i havve to talk more lowwbloods into playin these roles and that is so flippin borin',
'i will trade you the lowwbloods for one of your darkest most turbulent grimmest of shade pitchest of black outright flippin stygian hatesnogs',
'i knoww man i knoww',

            // HOSPITALITY - PARADOX SPACE

'there wwe go',
'hope youre singin a dirge cause itll be the last tune you--',
'fucks sake wwhat the fuck are you doin here',
'you fuck',
'your head on a fuckin platters wwhats up if you dont get out the damn wway you greasy faced vvile breathed dirt under fingernailed piece of uh shit',
'i hate angels so god damn much wwhy do they got to be so creepy wwhat did i evver do to deservve this wwhispers in the wwind bullshit',
'and wwhile im at it wwhat did i evver do to deservve havvin you of all people around',
'couldnt be a cute girl or a boy wwith maybe some nice muscle definition no got to be your flabby ass doesnt evven vvisit on purpose',
'wwhy do the starvvin alwways talk about food same fuckin thing a man got needs',
'you just dont get it my loneliness is a fate wworse than death darker than the deepest ocean colder than the highest fuckin mountain',
'wwhat do you do if you got a song in your heart but no one to share it wwith huh',
'... evverythins just so easy for you isnt it',
'look this might be hard for you to understand but im a fuckin tsunami of tumultuous emotion okay',
'life death all poundin against the shore of my thinkpan swweeps of military dignity and grace this shits beyond your comprehension dont evven try it',
'thats not a pill thats a slice of doped up pie you charlatan get that toxic shit awway from me',
'uggghhhhh',
'alright here wwe are',
'this leads back to my hivve so you can get up the second gate and fuck out of my life',
'yes because i fuckin hate you dont count on it noww fuck OFF fuck you', 
'wwoww wwhy didnt he insist on stayin harder some people just dont havve basic consideration for others i swwear',
    
            // SUMMER TEEN ROMANCE - PARADOX SPACE
'this dumps got nothin on my hivve',
'no',
'WWHAT',
'just bury me just bury my wwhole face',
'yeah of boredom lmfao',
'OWW',
'huh y-you too',
'wwell i dont really feel like it but i guess ill come if you dwweebs really wwant me too',
'not so fast',
'i cant let you do that buoys',
'not wwithout incurrin my friends r-anchor or i guess just anchor wworks as a fish pun there too wwhatevver',
'hey guys',
'they nevver gave me a uniform they just wwanted me for my body specfically my gills once i recovvered the secret treasure from the bottom of the lake the sburbs cast me aside',
'wwhen they said they could use a guy like me at camp sburb they meant it HEY DONT IGNORE ME',




        ];

      
      var wordNum = Math.floor(Math.random() * theWord.length);
      
     
      output.textContent = theWord[wordNum];
    }