var btn = document.querySelector("button");
    var out = document.getElementById("output");
    
  
    btn.addEventListener("click", getWord);
   
    function getWord(){
     
      
      var theWord= [
        
        // WEBCOMIC

        'maybe ii ju2t want two giive the red and blue thiing a re2t for a change and not make iit 2o iit2 liike, oh look iit2 that prediictable fuck wiith tho2e two 2tupiid color2, iit2 amaziing how much everyone fuckiing hate2 hiim.',
        'iill 2end you the download 2oon, talk two you later.',
        'ii am goiing two diie. ii mean we all are. but e2peciially me. ii am goiing two get my a22 2erved two me twofold. double the 2erviice.',
        'iit2 kiind of liike how a prophet earn2 hii2 2triipe2, by beiing bliind, liike how an angel earn2 iit2 wiing2.',
        'ok that2 ju2t 2ome per2onal priivate emotiional ii22ue2 and iim dealiing wiith that, and hone2tly iid appreciiate you not alway2 throwiing that iin my face every goddamn opportuniity you get. liike thii2 ii2 a biig ciircu2 act two you, and that ii2 your 2peciial clown piie.',
        'ok well toniight2 not about fun, thii2 ii2 2eriiou2. deliiriiou2ly 2o. we are iin 2meariiou2 2hiit2taiin ciity. ',
         'wiill you at lea2t be able two leave the voiice2 behiind?',
         'wow what a my2teriiou2 thiing two 2ay, ii am 2o iintriigued.',
        'relay a me22age for me, tell them two go haunt my huge creakiing bone bulge.',
        'eheheh ii ju2t took an embarra22iing viideo of you cuttiing loo2e there, boy ii 2ure hope thii2 juiicy nugget doe2nt wiind up on the iinternet!',
        'iit wa2 liike the handle wa2 a bald guy goiing really fa2t, and ii wa2 hii2 twoupee.',
        'fuck thii2 confu2iing ca2te 2y2tem.',
        'god ii am ju2t bulge deep iin the fecal matter of a wiildly iincontiinent hoofbea2t but ok, iill iindulge you.',
        'you mean for good, wiill ii 2ee you agaiin?',
        'ii al2o talk two you becau2e iin ca2e you havent notiiced ii de2pii2e my2elf and perpetually 2eek two dupliicate through emotiional paiin the cacophony of phy2iical paiin my hiideou2 mutant braiin cau2e2 me every day.',
        'why dont we pretend there ii2 no 2pooky paranormal phenomena goiing on ju2t once and talk about what you wanted two talk about.',
        'ii gue22 ii dont fiind the whole my2tery of the ruiin2 a2 exciitiing a2 you, ok? ',
        'pretty 2weet aa.',
        'yeah, well, ii gue22 thii2 ii2 the kiind of 2hiit you have to deal wiith when two p2ychiic2 talk to each other about 2tuff.',
        'KK dont fliip your 2hiit about thii2 but iim 2ettiing you up two play a game wiith 2ome people.',
        'oh no are you iinto miiracle2 now two becau2e iif you are youre fiired preemptiively from the game.',
        'ok niice.',
        '2crew you vanta2 thii2 2hiit2 more real than kraft grub2auce.',
        'iif you heard what ii heard every niight ii mean WOW FUCK.',
        'KK iim 2orry but really iit2 kiind of a priivate matter between me and her and iid appreciiate iit iif that wa2 re2pected.',
        'youre lucky iim 2o fuckiing magnaniimou2 and chariitable cau2e otherwii2e there2 no chance iid wa2te my tiime on you.',
        'oh fuck that noii2e iin every leakiing oriifiice iit2 got you know ii hate the combiined product of you and my2elf more than you could ever begiin two hate me and my2elf and you and your2elf on your wor2t day 2o FUCKIING DEAL WIITH IIT.',
        'yeah ii am 2uch an iidiiot for not rewardiing your bubbly per2onaliity and iimpeccable people 2kiill2 wiith a leader2hiip giig. what an iincon2iiderate knuckle2ponged a22hole ii have been.',
        'thii2 ii2 2o iimmature, iim ba2iically ju2t laughiing here at how iimmature you are.',
        'you arent iin any po2iitiion two que2tiion my competence. youre the wor2t programmer iive ever 2een, you dont know anythiing about computer2, why do you bother.',
        'oh no, more chiildii2h burn2, ii dont have two prove anythiing two you, iim a great hacker, periiod.',
        'KK DO NOT RUN THAT CODE.',
        'eheheh makiing fun of people2 reliigiion2 ii2 the be2t thiing two do.',
        'eheheheheh KK iim ba2iically ju2t lmao here at thii2, WOW.',
        'dude dont worry ii wont fuck up your memo for long, ii ju2t cant beliieve thii2 wa2 the biig rea2on you wanted future me two help you open tho2e port2. two ba2iically ju2t babble about paradoxe2 and argue wiith your2elf for hundred2 of page2 heheheh.',
        'no man iit2 true, we are bulge bumpiing pupa pal2 agaiin.',
        'hey kk mo2t of the2e computer2 are 2hiit. 2o unle22 youve got a real good rea2on ii dont thiink iim gonna bother fiixiing them.',
        'fuck you and your priimadonna garbage, iim not goiing two break down 2obbiing becau2e you pa22 out at the 2iight of a liittle blood, why dont you man up.',
        'what diid you want me two do get down on the floor and kii22 your faiinted corp2e on the lii2p two wake you up on a nonexii2tent pro2piit?',
        'yeah ok fiine.',
        'whatever, iim pretty commiitted two not haviing anythiing two do wiith them ever.',
        'ok. what about pa2t you, ii2 pa2t you cool.',
        'eheheheheheheh.',
        'THANK you. kk, you are a true friiend.',
        'ehehehheheheheheh, yeah.',
        'ii 2aiid whatever.',
        'ehehehehe.',
        'yeah, of cour2e there2 no room, iit wa2 kiind of a moroniic iinviitatiion two be hone2t.',
        'maybe ii am not the two triick hoofbea2t you want two make me out a2.',
        'maybe iit2 makiing me turquea2y.',
        'but iim 2tiickiing wiith red and blue 2o maybe you 2hould 2uck on iit.',
        'ii ju2t know what iive 2een iin my vii2iion2.',
        'liike two dude2 on doublebutler ii2land. gettiing worked over by a 2iiame2e twiin ma22eu2e.',
        'paradox 2pace u2e2 them two u2her iin the end.',
        'oh 2h11t 11t2 onnnnnn 2uck4.',
        'you all can troll the2e iincompetent aliien2 all you want, iit wont change anythiing.',
        'iill ju2t be over here waiitiing two diie wiith diigniity, ok well maybe iit2 two late for that, but ju2t diie ii gue22, and yall can 2uck iit biitche2.',
        'whatever.',
        'ii dont get why youre RPiing about thii2, iit doe2nt make 2en2e, youre all out of your fuckiing 2ponge2.',
        'who2 thii2 doucebag?',
        'ok.',
        'bam, done.',
        'ii am fuckiing iincrediible.',
        'maybe they know we made them? maybe iit2 liike a tiip. liike thank2 dude2 for makiing u2 exii2t.',
        '2o ii gue22 you could 2ay... theyre the numeral2 of the bliind profiit2.',
        'man, ju2t... go away.',
        'iim not iin the glubbiing mood.',
        'oh GOD, iit2 hiim.',
        'ff can you tell hiim two go away, ii dont even have the energy for thii2.',
        'w/e bro, not iintere2ted.',
        'thii2 ii2 the mo2t hiilariiou2 thiing iive ever heard, he made one of hii2 2hiitty fake wand2 glow a liittle and now he thiink2 he2 a faiiry god troll or 2omethiing, lmao!',
        'AHAHAHAHA, ok that2 iit, he2 lo2t iit.',
        'ii 2hould have kiilled you on lobaf when ii had the chance.',
        'oh well, gue22 iit2 only fiittiing iid take you down iin ROUND TWO.',
        'you ready, priince?',
        'what iidiiot thought thii2 wa2 the iideal thiing two chiill out on. oh that2 riight, a braiindead clown who eat2 toxiic 2liime.',
        'you probably liike iit becau2e iit2 liike a coral reef or 2ome horriible jagged underwater piile of 2hiit liike that.',
        'ff come on we were haviing a priivate conver2atiion here.',
        '2iiiigh, HOLY 2HiiT, ye2 let2 talk about all my problem2 openly, ii LOVE that. hey kk, check thii2 out, my emotiion2 are 2erviing a2 entertaiinment agaiin!',
        'anyway, yeah, now that aa ii2 gone forever ii feel more depre22ed and u2ele22 than u2ual, and ii wa2 already pretty cod damn u2ele22 two begiin wiith, let2 face iit.',
        'you are 2o riidiiculou2ly optiimii2tiic iit2 kiind of 2iickeniing, why do you even put up wiith me?',
        'iif you werent 2o great ii would thiink you were a fuckiing iidiiot for liikiing me. 2o, ii gue22 thank2 for liikiing me? waiit, that 2ounded 2o pathetiic, oh god. ii 2hould probably take that back.',
        'KANAYA WHAT THE FUCK ARE YOU 2TIILL DOIING HERE, GOD DAMN IIT, CANT A GUY GET A LIITTLE GLUBBIING PRIIVACY WIITH A FII2H GIIRL IIN A PIILE OF HORN2.',
        '2o ii gue22 you 2hould be pretty happy when we fiinally get out of here?',
        'ii2nt that kiind of depre22iing? the thought that they miight 2tay wiith you tiil you diie?',
        'wow FUCK.',
        'that wa2 2o much more depre22iing than the thiing ii ju2t 2aiid.',
        'terezii wa2 riight, you are 2uch a drag two talk two the2e day2.',
        'do me a favor and 2pare me your 2pooky conundrum2 twoniight, youre kiind of pii22iing me off.',
        'oh ii dont know, maybe becau2e we are 2uppo2ed two 2ave the world twogether???',
        'oh my god ii ju2t had a breakthrough!!!',
        'thank you 2o much for thii2, iit wa2 great.',
        'that wa2 a joke, here type "ha".',
        'now type iit agaiin.',
        'there you go, you are now offiiciially the liife of the party.',
        'ok. thank you for 2ayiing 2o.',
        'have you ever been angry?',
        'ii dont remember you gettiing angry about anythiing.',
        'why dont you a2k karkat, he2 way angriier than me.',
        'for that matter why dont you get on HII2 ca2e about iit iin2tead of MIINE.',
        'iif you thiink we are goiing two faiil why wouldnt you get mad about that?',
        'at the voiice2 2endiing you down thii2 bliind alley the whole tiime?',
        'the fuck??',
        'ii dont want two play anymore then.',
        'fuck that ju2t watch, thii2 2hiit ii2 du2ted.',
        'check me out, all du2tiing iit liike a 2aucy fuckiin maiid.',
        'who care2, iim yankiing the grubtube on thii2 overpunctured biitch.',
        'iim telliing red team leader two forget the whole thiing.',
        'iim quiittiing a2 blue team leader.',
        'iif you want two 2hamble through thii2 macabre fanta2y of your2 2olo be my gue2t.',
        'are you me22iing wiith me??',
        'you do realiize iim p2ychiic two.',
        'ii could pull 2o much triippy 2hiit out of my 2piinal creviice, iit would make your head 2piin liike dervii2h iin a fuckiing blender.',
        '2o GET OFF YOUR HIIGH HOOFBEA2T.',
        'huh???',
        'up where.',
        'hello??????????????',
        'aradiia ii would liike two apologiize, ii flew off the handle there.',
        '2o iim 2orry, iit wa2 my fault.',
        'ii hope we are 2tiill friiend2.',
        '2o anyway, ii thiink even though ii quiit a2 leader iim 2tiill goiing two play the game now.',
        'becau2e iit2 eiither that or get totally creamed by all the2e fuckiing 2pace boulder2.',
        'hey maybe we can make the be2t of the game anyway, even though ii guess we are goiing two lo2e.',
        'oh my god!!!',
        'youre goiing two giive me 2hiit agaiin???',
        'after ii crawled on my belly liike that all groveliing at you.',
        'liike 2ome low cla22 guy wiith... whatever color blood ii2 lower on the hiierarchy than miine.',
        'what2 wor2e than yellow?',
        'anyway 2crew you, iim playiing thii2 game riight now.',
        'waiit what2 thii2...',
        'are you heariing that 2pooky me22age from the grave?',
        'iit ii2 from my abiiliity two giive a 2hiit. whiich ju2t diied.',
        'thii2 ii2 where you laugh agaiin!',
        'why.',
        'b2.',
        'ii dont 2ee anythiing out there.',
        'here ii go!',
        'hii?',
        'aradiia, ii am riight glubbiing here, liike two feet away from you.',
        'iif you want two 2ay 2omethiing two me why dont you ju2t turn two your left and 2ay iit, iit2 bad enough that youve hardly 2aiid two lou2y word2 two me 2iince you became that 2weaty a22hole2 2moochbot.',
        'how ii2 iit hard.',
        'you are a tiin can, robot2 dont have feeliing2.',
        'ok then, what ii2 iit.',
        'what, where are you goiing?',
        'er, cool ii gue22??',
        'waiit.',
        'what the hell i2 that 2uppo2ed two mean?',
        'hey what2 up aa.',
        'wont ii?',
        'wa2 iit the matchiing ruiin2 2iite?',
        'ii dont know, ju2t a weiird feeliing. ',
        'ii feel liike we had thii2 conver2atiion before and that2 what iit wa2 about.',
        'probably nothiing. but now not only doe2 iit feel liike we had the conver2atiion before, but iit2 goiing diifferently thii2 tiime.',
        '2o iit2 extra weiird. maybe your voiice2 are iinvolved?',
        'ii dont hear a goddamn thiing.',
        'do you?',
        'oh well.',
        '2orta.',
        'ii gue22.',
        '2ure.',
        'how can ii help, then.',
        'oh yeah, ii am awe2ome about that for 2ure.',
        'but, ii cant 2hake the feeliing the2e ruiin2 are goiing two be nothiing but trouble for u2.',
        'that2 becau2e iit2 fuckiing true about everythiing!',
        'liike what?',
        'hey diidnt you al2o fiind 2ome biit2 and piiece2 of your biizarre robot doppelganger.',
        'ii dont know, ii ju2t "remembered" 2ome more 2hiit about thii2 dii2covery, god 2orry.',
        'why dont we piick thii2 up agaiin later when were not feeliing 2o weiird?',
        'what the fuck?',
        'becau2e you fliip your 2hiit about everythiing.',
        'eheheheheh riight on but let2 2hut our mouth2 a 2econd and talk about thii2 game.',
        'iitll only be a 2econd really you dont have two do two much.',
        'well the 2hort 2tory ii2 that iit2 an iimmer2iive 2iimulatiion that you play wiith a group.',
        'the long 2tory ii2 that the fate of our ciiviiliizatiion depend2 on u2 playiing iit.',
        'heh ii gue22 the long one wa2 2horter than the 2hort one FUCK.',
        'no no.',
        'more liike ii adapted iit.',
        '2ome crazy technology AA dug out of 2ome ruiin2.',
        'havent you talked two her about iit?',
        'probably iit2 becau2e mo2t troll2 are.',
        'ii told you liike a biilliion tiime2 ii cant do that you nub2lurping fuckpod.',
        'ok how about you take your own adviice you are 2uch a blubberiing hypocriite.',
        'nobody hate2 hiim2elf more than you iidiiot.',
        'ok well iill 2end you a download 2oon.',
        'iim 2ett1ng up two team2.',
        'liike two 2eparate competiing team2 2o that there2 a better chance of at lea2t one group wiinniing.',
        'and al2o ii gue22 two 2ee which one can wiin fa2ter.',
        'youre on the red team.',
        'ii wiill be the leader of the blue.',
        'uh...',
        'bro youre not the red team leader.',
        'ii piicked GC for that.',
        'dude ii diid NOT thiink youd be iintere2ted iin thii2 dont act all offended.',
        'ii know your fiilthy 2eedflap ii2 flutteriing iin the profane breeze that2 2hootiing out your 2tiinkiing meal tunnel.',
        'ii do know that much.',
        'liike ii really giive a fuck who the red leader ii2. you want two be the leader fiine talk two GC about iit.',
        'eheheheh you LIITERALLY a2k me that every tiime are you jokiing.',
        'ii cant even tell anymore.',
        'yeah ok.',
        'hey change of plan, we arent playiing thii2 game anymore.',
        'ii know, 2he told me, ii dont care.',
        'the game ii2 bad new2, iit wiill cau2e the end of the world, not 2top iit.',
        '2o forget iit, ju2t go back two whatever you were doiing. wriitiing your 2hiitty code or whatever.',
        'oh god. no you iidiiot, ii dont care about the game anymore.',
        'ii ju2t quiit, iim not playiing, you 2hould two.',
        'oh liike you havent 2aiid that liike a biilliion tiime2.',
        'the only thiing youre good at ii2 yelliing and makiing huge mii2take2. and beiing UGLY AND HORRIIBLE IN EVERY WAY, AND HAVIING 2TUPIID LIITTLE NUBBY HORN2.',
        'waiit, KK...',
        'no dont.',
        'oh god, no dont run that, iim 2eriiou2.',
        'iim not 2ure, but iit would be really, really bad iif you ran iit, ju2t dont.',
        'you are the dumbe2t grubfucker on the planet, ii 2wear.',
        'hello??????????????',
        'oh my god.',
        'a few liine2 down, after ii pretend liike iim goiing two diie.',
        'iim 2ure for a laugh on account of my iimmiinent banniing, FUCK how could you even do that two me.',
        '2o cold man.',
        'eheh no bro were cool about that, now future you ii2 connectiing wiith me 2o ii can enter the game.',
        'yeah 2o thank2 for that fiive hour2 iin advance.',
        'nooooooo, not the ban, it buuuuuuurn2, oh god hahahaha. waiit. oh god. iit doe2 burn.',
        '2omethiing2 wrong, iim 2eriiou2!',
        'that horriible p2ychiic noii2e',
        'the voiice2', 
        'theyre all goiing two diie',
        'oh 2HiiT iim bleediing',
        '2hiiiiiiiiiiiiiiiiiiiit',
        'thii2 ii2 bad',
        'ii have two get her iin quiick',
        'got two go',
        'yeah ii hate to 2ay iit, but iit really 2ort of ii2.',
        'no not at all, theyre u2ele22 and uniintere2tiing liike iim 2ure you already gathered.',
        'ii recommend we dont bother wiith them, though aradiia 2eem2 two thiink well all be iin each other2 2ponge2 iineviitably.',
        'uh huh, 2ure kk by the look of 2ome of your future memo2 iit look2 liike youre gonna get pretty wound up by thii2 thiing 2oon.',
        'no way, theyre hiilariiou2, be2t thiing about haviing you a2 a leader hand2 down.',
        'ii dunno man, ii have heard nary a honk out of hiim for a whiile.',
        'yeah after you got me kiilled iin the fiir2t place.',
        'TZ you want two be the leader of one of the team2?',
        'yeah.',
        'ok ii diidnt 2ay anythiing about a red team, or even that there were two team2, but fiine.',
        'you dont know what iim goiing two do, 2top beiing a2 though you can read my miind.',
        'iit2 not a power you have, your 2trength2 are beiing bliind and triickiing people about 2tuff.',
        'maybe there ii2 more two me than you thiink.',
        'maybe red and blue arent that great and ii hate them 2uddenly, have you thought of that.',
        'maybe iim more of an aubergiine guy plu2 whatever that putriid color is you type wiith, what ii2 that, turqoii2e?',
        'maybe the new name for that color ii2 2ummer 2hiithead mii2t, have you con2iidered that?',
        'yeah ii thiink 2o.',
        'piick out whoever you want for the red team and iill lead the blue team.',
        'ii dont know yet',
        'that the world wiill end and our whole race diie2 and thii2 ii2 how we 2ave iit.',
        'and aa can back me up on thii2 2o dont be all doubtiing me about iit.',
        'mo2tly, what doe2 that mean?',
        'but before ii diie, iim goiing two go bliind liike you.',
        'iit ha2 two happen liike that.',
        'iim not 2ure why, but ii thiink iit2 liike...',
        'fulfiilliing 2ome requiirement for a true prophet of doom.',
        'iin order for the vii2iion2 two be riight, that ha2 two happen, and the uniiver2e wiill make 2ure iit wiill.',
        '2ome terriible mythiical demon.',
        'wiith the2e awful feathery wiing2.',
        'huh??',
        '2o yeah.',
        'we wiill all diie but mo2t e2peciially me, end of 2tory.',
        'what do you mean.',
        '2eriiou2ly talk two aa 2he wiill corroborate everythiing. you and 2he are pretty tiight arent you?',
        'you dont have two bother recruiitiing, 2orry two wa2te your tiime.',
        'he ii2?',
        'ok that wa2 faiirly prediictable but that2 fiine.',
        'iill talk two hiim about iit.',
        'nothiing, thii2 game 2uck2 and aa ii2 full of crap.',
        '2orry about all thii2.',
        'ii already told KK what ii thought about thii2 awful iidea.',
        'iit ju2t make2 NO 2en2e, you can count me out.',
        'you all can troll the2e iincompetent aliien2 all you want, iit wont change anythiing.',
        'why dont you ju2t u2e our name2.',
        '2omeone 2ent you money?',
        'why2 2omeone 2endiing you money.',
        'and why now of all tiime2, liike we can even u2e iit.',
        '2omeone iin our uniiver2e.',
        'no no, ii mean 2omeone from OUR uniiver2e, the one we ju2t made.',
        'yeah 2ure but we are completely out2iide iit2 temporal envelope remember.',
        'the entiire hii2tory of the thiing exii2t2 already iin iit2 entiirety from our per2pectiive, iit2 flow of tiime mean2 nothiing two u2.',
        '2o we dont have two waiit for anythiing, iit2 all already there.',
        '413 boonbond2? damn.',
        '2omeone here ha2 been playiing 2grub ii gue22. wonder why theyd 2end u2 money.',
        'why 413, why that number. any iidea?',
        'well, 2eeiing a2 we dont know 2hiit about the guy...',
        'bliind 2eem2 liike the operatiive concept.', 
        'kiinda liike a bliind donatiion. and now were fuckiing riich.',
        'yeah.',
        'ehhhhh, thii2 2hiit2 probably not iimportant enough two bother hiim wiith.',
        'iif he fiind2 out, hell probably want two hatch 2ome dumba22 plan that make2 no 2en2e. and badger me iintwo doiing a lot of miindnumbiing bu2ywork.',
        'iid leave hiim alone.',
        'here come here iill open hiim up iin a viiewport.',
        'let2 2hed 2ome... LIIGHT on the 2ubject.',
        'that wa2 the joke 2hut the fuck up.',
        'are you 2tiill 2pyiing on that iin2ufferable priick.',
        '2eriiou2ly a dude giive2 a giirl a few buck2 and 2uddenly 2he cant keep her no2e off hiim, iit ii2 2o prediictable.',
        'you thiink iim cool?',
        'dont 2ay half the tiime. oh god ii walked riight iinto that one diidnt ii.',
        'ehehehehe, thii2 party ii2 a fuckiing JOKE.',
        'niice dress, fiin face, olol.',
        'ok, iim pretty much 100% po2iitiive 2he2 not actually doiing that, but ok.',
        'al2o let2 get real, thii2 horn piile ii2nt comfortable at all, iive got hard metal edge2 jabbiing me everywhere, and iit2 lumpy a2 hell, and you cant move a fuckiing iinch wiithout honkiing the 2hiit out of iit and makiing everyone iin the room look at you.',

        // PESTERQUEST
        
        'thii2 ii2 2o fuckiing typiical! he diidnt even fuckiing a2k... ju2t.. fuck! he cant miind hii2 own fuckiing bu2iine22.',
        'not all of your friiend2 have two be friiend2 wiith each other why ii2 that 2o fuckiing hard for hiim two under2tand.',
        'oh 2o youre double teamiing me now.',
        'can ii help you dude?',
        'okay.',
        'that 2ound2 liike bull2hiit but iill beliieve iit 2iince ii dont want two make thii2 any more awkward.',
        'iim 2ollux.',
        'youve been me22agiing me for day2 dude. and been totally weiirdly iinva2iive two me.',
        'whatever iim iin a good mood today 2o were 2tartiing over.',
        'ii dont thiink you get how weiird youre beiing. ii havent told you anythiing about me but 2omehow you manage two know a lot of really per2onal iinformatiion about me.',
        'ii know youre friiend2 wiith ba2iically all of my friiend2. and iim 2ure they told you iim kiind of an aloof piiece of 2hiit and grumpy and hard two get along wiith. and half the tiime ii feel liike ii dont even de2erve them.',
        'iim way more complex than whatever the fuck ii 2ay onliine and what my friiend2 have told you. real liife ii2nt liike a datiing 2iim iin whiich you fumble your way iinto the riight choiice. why do you even want two friiend me?',
        'whether ii want iit or not iim de2tiined two be a war machiine.',
        'ii dont thiink you under2tand how thiing2 work for people liike me.',
        'ii had a wake up call iin whiich ii realiized nothiing ii do really matter2.',
        'iim 2tupiid enough that iill re2ii2t. 2o iit wiill defiiniitely 2uck biig tiime for me.',
        'but ii already made the mii2take of tru2tiing 2omeone who let me beliieve ii could make a change. but 2hiit2 got fucked and that2 that.',
        'ii can 2ee why the other2 miight liike you. and for whatever it2 worth, ii do wii2h ii could beliieve you two.',
        'no you recycled a22wiipe.',
        'the voiice2 of the dead. or more iimportantly, the iimmiinently decea2ed.',
        '2orry ii got really 2tre22ed for a moment.',
        'fuck, thii2 ii2 awkward.',
        'dude you have got two 2top beiing 2o overeager iit2 a liittle embarra22iing.',
        'that2 niice but were goiing two arriive wiith more 2tyle.',
        'brace your2elf. ii refu2e two 2low down.',
        'cant a dude ju2t be 2uper fuckiing jazzed about publiic tran2portatiion.',
        'fuck the entiire planet and it2 2tupiid fuckiing hemo2pectrum 2y2tem, but at lea2t the traiin can take you where you need two go for the mo2t part.',
        'kn youre really kiiliing my viibe here.',
        'completely har2hiing iit.',
        'are we really doiing thii2 agaiin maryam.',
        'what happen2 ii2 that ii have biig braiin2 that ii2 almo2t a2 biig a2 my-',
        'then kn found goregle. and found term2 liike dopamiine, noradreliine and p2iiomiine. now 2he thiink2 2he know2 better than me.',
        'diid you try turniing iit on and off?',
        'no offen2e two you or kk, but kk ha2 no fiilter on who he let2 iinto hii2 liife.',
        'ii hate meetiing new people. do ii look liike ii know what the fuck a dave ii2? biitch iill kiill you.',
        'iit2 a meme.',
        'ii wouldnt miind 2pendiing more tiime wiith you. whiich ii2 2omethiing ii dont tell everybody.',
        'there2 a frozen musclebeast nectar place near the drone offiice.',
        'oh my god diid you 2eriiously ju2t call her that.',
        'what ii2 wrong wiith you.',
        'human2 dont even HAVE diifferent blood color2 you u2ele22 tool.',
        'and iive had enough of you.',
        'eat 2hiit and diie.',
        'iit would be my plea2ure.',
        'kk iif thii2 ii2 more whiiniing about the team leader2 ii dont want to hear it.',
        'you ju2t dont have the qualiitiie2 nece22ary for thi2 2ort of 2cenariio and iif youre ju2t here two 2tart 2ome 2ort of 2lap fiight for wriiggler2 then you 2hould probably go fuck your2elf.',
        'all that2 goiing two happen ii2 you 2ayiing 2omethiing you regret and then crytypiing over whether or not were 2tiil friiend2.',
        'ii miight have a deathwii2h but iim not 2uiiciidal.',
        '2o eiither tell me what crawled up your nook and laiid egg2 iin there or let me get back two work.',
        '2orry kk iim tryiing to wrap my pan around thii2 but iim pretty 2ure youre fuckiing wiith me.',
        'youre goiing two be a thre2hcutiioner you cant ju2t 2tart 2howiing up on cull lii2t2.',
        'ju2t come up here okay well fiigure thii2 2hiit out.',
        'you dont know anythiing about me or my deathwii2h kk. come up2taiir2.',
        'dont make me tell you how much ii hate you.',
        
        // PARADOX SPACE
        
        'what the hell do you want. go away.',
        'ii dont want two help you. leave me alone you 2weat-coated blii2terbag.',
        'kk couldnt program hii2 way out of two wet pulp sheet contaiiner2.',
        'what diid you break thii2 tiime.',
        '??',
        'er, you know ii cant program anythiing two fiix a phy2iical problem riight?',
        'fiine, iif you want help you fuckiing got iit hoof-head.',
        'youre welcome, you blue blooded brute.',
        'hmph.',
        'liike my headache2 arent bad enough a2 iit ii2...',
        'ugh, thii2 place ii2 a DUMP. good thiing ii brought my palmhu2k.',
        'were goiing two be murdered iin our 2leep.',
        'drug2 brand root beer. briilliiant marketiing 2trategy. dont tell though cau2e theiir adorable chiildliike naiivete ii2 a liivetweet goldmiine.',
        'oh my god, ii cant beliieve they diied! my palmhu2k2 preciiou2 batteriie2!',
        'you amateur2 need 2ome a22ii2tance?',
        'ju2t liike ii thought. thii2 ii2 my ~ATH.',
        'no 2marta22, the programmiing language, ~ATH.',
        'ii coded the ma2ter program theyre u2iing iin thii2 bomb.',
        'there! re2ettiing my own code ii2 no 2weat.',
        'now thii2 bomb wont go off untiil 2omethiing diie2 iin the iimmediiate viiciiniity!',
        'xenomorph-type fiidu2pawn are liike bee2. there2 a queen and 2he lay2 the egg2.',
        'ii 2hould have known that thii2 wa2 two good two be true. now were goiing two diie horriibly, arent we?',
        'viitriiol ii2 not helpiing eiither kk.',
        'your fruiitle22 anger iin the face of our iimmiinent demii2e warm2 my bloodpu2her2.',
        'iim goiing a2 fa2t a2 ii can.',
        'wow gro22.',
        'ii need an entiirely new 2et of friiend2. you are all maniiac2.',
        'al2o they re2cued your hat.',
      ];

      
      var wordNum = Math.floor(Math.random() * theWord.length);
      
     
      output.textContent = theWord[wordNum];
    }
